### ISSUE TITLE
Spigot 1.8.6

### ISSUE THREAD

**Issue by somenet** [CoreNetwork/TradeCraft#50]
Ohai!
Just a friendly reminder: Spigot 1.8.6 is out.
Currently running on that version will throw an exception on server startup:

java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Entity
        at us.corenetwork.tradecraft.TradeCraftPlugin.onEnable(TradeCraftPlugin.java:27) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-c5146ba-c637b93]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-c5146ba-c637b93]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Entity
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-c5146ba-c637b93]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-c5146ba-c637b93]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]

**Comment by Cleyra** [comment]
The plugin was updated to Spigot 1.8.6 about 30 minutes ago. Grab the latest version!
